---
- name: config | configuring apm-server
  template:
    src: etc/apm-server/apm-server.yml.j2
    dest: /etc/apm-server/apm-server.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - restart apm-server
  become: true
