---
# tasks file for ansible-es-apm-server
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config.yml
  when: es_apm_server_config|bool

- include_tasks: service.yml
